// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oudceonewduhsfhyiiny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91ZGNlb25ld2R1aHNmaHlpaW55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg2OTQ2MjMsImV4cCI6MjA5NDI3MDYyM30.Y-00fM7KzOBfalboFcVC9ojcw96RY8JXI8vDvBv1yGQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});